language: python
python:
  - "2.7"
install:
  - sudo apt-get update
  # All of the following apt installed packages are build dependencies of
  # cyipopt.
  - sudo apt-get install gfortran libblas3gf liblapack3gf liblapack-dev libmumps-dev
  - sudo apt-get install coinor-libipopt1 coinor-libipopt-dev
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip sympy numpy scipy cython nose coverage
  - source activate test-environment
  - pip install https://bitbucket.org/moorepants/cyipopt/get/tip.zip
  - python setup.py install
script:
  nosetests -v --with-coverage --cover-package=opty
